### ISSUE TITLE
Crash silently

### ISSUE THREAD

**Issue by samdark** [deemru/php-cgi-spawner#3]
Currently in case of segfaults a dialogue pops up and prompting to debug it. Since spawner is able to restart crashed processes it's a good idea to suppress these dialogues.

![qip shot - screen 385](https://cloud.githubusercontent.com/assets/47294/11843313/0e60b1c6-a41a-11e5-8580-5b88c84ca143.png)

I think this is related: https://stackoverflow.com/questions/9718695/how-can-i-supress-all-error-dialogs-when-a-process-crashes-i-only-want-it-to-cr

**Comment by deemru** [comment]
Yep, it can be done in 1 line:

> SetErrorMode( SEM_FAILCRITICALERRORS | SEM_NOGPFAULTERRORBOX );

But do you think it is a good idea to suppress such errors?

For example, if a user do not have an appropriate vcredist installed he will never know that is wrong. And spawner will eat CPU trying to run php-cgi. Or some hacks can be exploited unnoticable. 

Personally, i never catched segfault in php-cgi. The restart functionality was added because php-cgi simply disappears sometimes while running other applications through exec().

**Comment by samdark** [comment]
Just silencing, of course, isn't a good thing to do by default. Ideally I'd prefer logging instead of dialogues.

**Comment by deemru** [comment]
Let's add a fourth argument as a number of milliseconds to delay between php-cgi restarts: if it is not zero value we SetErrorMode to crash silently.

Would it be enough?

Logging is a good suggestion, but do we need a smarter app? Currently it is stated as a minimal and simple.

**Comment by samdark** [comment]
To me personally an optional way to silence crashes would be OK.

**Comment by deemru** [comment]
Pre-release is ready: https://github.com/deemru/php-cgi-spawner/releases/tag/1.0.18

Close the ticket if it's good.

**Comment by samdark** [comment]
Tested briefly. It is good.
